replicaCount: 2

image:
  repository: 164253013547.dkr.ecr.us-east-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

configMap:
  SECRET_KEY: "django-insecure-dev-key"
  DEBUG: "1"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "app_db"
  DB_USER: "app_user"
  DB_HOST: "db-postgres-service"
  DB_PORT: "5432"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  secret:
    dbPassword: "qwerty123"
    secretKey: "qwerty123-qwerty123"